#TEST ENVIROMENT CONFIG
version: '3.3'
## app version: 1.1
services:
    traefik:
        image: 'traefik:v2.2'
        container_name: 'traefik'
        command:
            #- "--log.level=DEBUG"
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
            - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
            - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
            - '--certificatesresolvers.myresolver.acme.email=ovezov3210@gmail.com'
            - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
        ports:
            - '80:80'
            - '443:443'

        volumes:
            - '/letsencrypt:/letsencrypt'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'

    frontendd:
        image: 'tipfurion/hackathon-2021-final:v1'
        container_name: 'frontendd'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.frontendd.rule=Host(`hackathon.kubernne.space`)'
            - 'traefik.http.routers.frontendd.entrypoints=websecure'
            - 'traefik.http.routers.frontendd.tls.certresolver=myresolver'
